FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY <<EOF /etc/nginx/conf.d/default.conf
upstream aci_backend {
    server qrforge-app-prod.northeurope.azurecontainer.io:8000;
}

server {
    listen 8080 default_server;
    server_name _;

    location / {
        proxy_pass http://aci_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }
}
EOF

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
