"""initial schema

Revision ID: 6335c06e104d
Revises:
Create Date: 2025-11-29 23:25:47.767549

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6335c06e104d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
